services:
  db:
    image: postgres:16
    container_name: ponto_db
    environment:
      POSTGRES_DB: ponto
      POSTGRES_USER: ponto_user
      POSTGRES_PASSWORD: ponto_pass
    ports:
      - "5432:5432"
    volumes:
      - ponto_db_data:/var/lib/postgresql/data

  api:
    image: node:20-alpine
    container_name: ponto_api
    working_dir: /app
    volumes:
      - ./api:/app
    environment:
      NODE_ENV: development
      PORT: 3001
      DATABASE_URL: postgres://ponto_user:ponto_pass@db:5432/ponto
    ports:
      - "0000:3001:3001"
    depends_on:
      - db
    command: sh -c "npm install && node src/server.js"

volumes:
  ponto_db_data:
